name: lovelydialogs
description: A set of simple wrapper classes that are aimed to help you easily create fancy material dialogs
version: 0.0.2
homepage: https://github.com/VictorHerbert/LovelyDialogs

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter: