name: lovelydialogs
description: Create fancy dialogs with ease
version: 0.0.1
author: Victor Herbert
homepage: victorherberts.firebaseapp.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: