name: lovelydialogs
description: A wrapper for good looking dialogs
version: 0.0.1
author: Victor Herbert

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter: